// <auto-generated />
namespace InventoryContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialize12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialize12));
        
        string IMigrationMetadata.Id
        {
            get { return "201704240804437_initialize12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
